--[[

    Please do NOT edit this file.
    The contents of this file will be generated automatically.
    
]]--
--- @type Namespace
local ns = select(2, ...)

local silent = true

--@do-not-package@
if ns.debug:IsDeveloper() then silent = false end
--@end-do-not-package@
local L = LibStub('AceLocale-3.0'):NewLocale(ns.addon, 'enUS', true, silent);


--[[-----------------------------------------------------------------------------
Localized Texts
-------------------------------------------------------------------------------]]
L['General'] = true
